services:
    web:
        image: nginx:latest
        expose:
            - "80"
        volumes:
            - ./html:/usr/share/nginx/html:ro
        networks:
            - traefik

networks:
    traefik:
        external: true